apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: menu
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
  # # Add a this finalizer ONLY if you want these to cascade delete.
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io
spec:
  # The project the application belongs to.
  project: default

  # Source of the application manifests
  source:
    repoURL: git@github.com:surveyplanet-training/menu-infrastructure.git
    targetRevision: HEAD
    path:
      manifests/menu/api

      # # Release name override (defaults to application name)
      # releaseName: guestbook
    # # directory
    # directory:
    #   recurse: true
    #   jsonnet:
    #     # A list of Jsonnet External Variables
    #     extVars:
    #       - name: foo
    #         value: bar
    #         # You can use "code to determine if the value is either string (false, the default) or Jsonnet code (if code is true).
    #       - code: true
    #         name: baz
    #         value: "true"
    #     # A list of Jsonnet Top-level Arguments
    #     tlas:
    #       - code: false
    #         name: foo
    #         value: bar

    # # plugin specific config
    # plugin:
    #   name: mypluginname
    #   # environment variables passed to the plugin
    #   env:
    #     - name: FOO
    #       value: bar

  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: menu

  # Sync policy
  syncPolicy:
    automated: # automated sync by default retries failed attempts 5 times with following delays between attempts ( 5s, 10s, 20s, 40s, 80s ); retry controlled using `retry` field.
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
      allowEmpty: false # Allows deleting all application resources during automatic syncing ( false by default ).
    syncOptions: # Sync options which modifies sync behavior
      - Validate=false # disables resource validation (equivalent to 'kubectl apply --validate=false') ( true by default ).
      - CreateNamespace=true # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.
      - PrunePropagationPolicy=foreground # Supported policies are background, foreground and orphan.
      - PruneLast=true # Allow the ability for resource pruning to happen as a final, implicit wave of a sync operation
    # The retry feature is available since v1.7
    retry:
      limit: 5 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 3m # the maximum amount of time allowed for the backoff strategy

  # Ignore differences at the specified json pointers
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
