apiVersion: apps/v1
kind: Deployment
metadata:
  name: menu-api
  namespace: menu
  labels:
    app: menu-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: menu-api
  template:
    metadata:
      labels:
        app: menu-api
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: menu-api
          image: lukamit/menu-api-development:0.1.0-prerelease76
          ports:
            - containerPort: 9001
          env:
            - name: LOCAL_ENV
              value: development
            - name: PORT
              value: "9001"
            - name: NODE_ENV
              value: development
            - name: MONGO
              valueFrom:
                secretKeyRef:
                  name: api-mongo
                  key: mongo
