apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: menu-api
  namespace: menu
  annotations:
    # General:
    # kubernetes.io/ingress.class: traefik
    #
    # TLS configuration:
    # traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
    # traefik.ingress.kubernetes.io/router.tls: "true"
    #
    # Middleware:
    # traefik.ingress.kubernetes.io/router.middlewares:my-middleware@kubernetescrd
spec:
  rules:
    - host: "api.labitup.one"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: menu-api
                port:
                  number: 9001
